services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_skin_story_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: